### ISSUE TITLE
got this when trying to pair

### ISSUE THREAD

**Issue by llyons92** [edc1591/homebridge-theater-mode#1]
when i run npm install -g node-appletv
i get this

> sodium@2.0.3 preinstall /usr/local/lib/node_modules/node-appletv/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /usr/local/lib/node_modules/node-appletv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
make: *** [libsodium] Error 1
/usr/local/lib/node_modules/node-appletv/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-appletv/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Luke/.npm/_logs/2018-03-24T01_10_00_225Z-debug.log

**Comment by evandcoleman** [comment]
Try this, for macOS `$ brew install libtool autoconf automake`, or on Linux `$ sudo apt-get install lib tool autoconf automate`

**Comment by llyons92** [comment]
Will do thanks

**Comment by evandcoleman** [comment]
Closing for lack of activity. Reopen if the issue is not resolved.

**Comment by llyons92** [comment]
brew: command not found 
getting this now

**Comment by evandcoleman** [comment]
Did you try installing [homebrew](https://brew.sh)?

**Comment by llyons92** [comment]
Installed homebrew,but when trying to install the plugin I get this: n file included from ../src/dns_service_browse.cpp:1:
In file included from ../src/mdns.hpp:12:
In file included from ../node_modules/nan/nan.h:190:
../node_modules/nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/Users/Luke/.node-gyp/9.4.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/Luke/.node-gyp/9.4.0/include/node/v8config.h:321:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
In file included from ../src/dns_service_enumerate_domains.cpp:1:
In file included from ../src/mdns.hpp:12:
In file included from ../node_modules/nan/nan.h:190:
../node_modules/nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/Users/Luke/.node-gyp/9.4.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/Luke/.node-gyp/9.4.0/include/node/v8config.h:321:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^


continuously

**Comment by llyons92** [comment]
> sodium@2.0.3 install /usr/local/lib/node_modules/homebridge-theater-mode/node_modules/sodium
> node install.js --install

echo Build node-sodium module
Build node-sodium module
node defines.js
Extracting DEFINES from Libsodium make file...
Detected system architecture x64
Libsodium Makefile : ./deps/libsodium/Makefile
Please run autogen.sh and configure in ./deps/libsodium directory first
{ Error: ENOENT: no such file or directory, open './deps/libsodium/Makefile'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './deps/libsodium/Makefile' }
node-gyp rebuild
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/sodium/src/crypto_aead.o
In file included from ../src/crypto_aead.cc:8:
../src/include/node_sodium.h:22:10: fatal error: 'sodium.h' file not found
#include "sodium.h"
         ^~~~~~~~~~
1 error generated.
make[1]: *** [Release/obj.target/sodium/src/crypto_aead.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-theater-mode/node_modules/sodium
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
make: *** [nodesodium] Error 1
/usr/local/lib/node_modules/homebridge-theater-mode/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-theater-mode/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
/usr/local/lib
└── (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Luke/.npm/_logs/2018-04-22T01_50_46_884Z-debug.log

**Comment by evandcoleman** [comment]
Do you have Xcode installed? Make sure it is and then run `xcode-select --install`
