### ISSUE TITLE
LIbsodium and libtools error constantly unable to install

### ISSUE THREAD

**Issue by jblakeney82** [edc1591/homebridge-theater-mode#11]
Hello, 

This plugin will not install. I have followed every instruction and troubleshooting guide on the web and still nothing. I keep getting the libtools and libsodium errors as in they don't exist however they have been installed and show up to date with the current version. 

Not sure what else can be done. REALLY want to get this plugin to work. 

please help thanks!

**Comment by lyret** [comment]
If you running on a mac; try installing automake using Homebridge

`brew install automake`

**Comment by beeper99** [comment]
no does not help, any other ideas?

**Comment by jblakeney82** [comment]
You guys or anyone actually able to get this plugin to work? Been months of trying everything on the web and no results

**Comment by beeper99** [comment]
no luck here, identical issue as you (MacOS 10.14.1)

**Comment by jblakeney82** [comment]
I’m running a Pi actually but same thing, even with the other DACP or AppleTV plugins, all the same type of error

**Comment by ptrvg** [comment]
I had it running and also dacp on a pi. It used to work although a bit slow. That is why I switched to dacp because my hue lights react much faster on play pause events with the dacp plugin. Then at some point dacp stopped working. I then checked theater-mode and it has also stopped working. My guess is a tvOS update is the cause.

**Comment by beeper99** [comment]
homebridge-plex-sensors still works if it helps.

**Comment by jblakeney82** [comment]
Yeah I am not a fan of plex and I was using that as well and then stopped working haha I removed and re added and changed ports and web hooks etc.. and no dice. 

Thanks for the help!

**Comment by evandcoleman** [comment]
Can you post the actual error you're getting?

**Comment by jblakeney82** [comment]
Thanks for the reply. 

Just ran the install with unsafe perm again and now it went through a long installation process but still ended with Sodium errors


Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/opt/nodejs/lib/node_modules/homebridge-theater-mode/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-02T22_45_17_820Z-debug.log
pi@raspberrypi:~ $

**Comment by jblakeney82** [comment]
I get this before any installation of Homebridge-Apple-tv, or DACP or Home theater mode

> sodium@2.0.3 preinstall /opt/nodejs/lib/node_modules/homebridge-apple-tv/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /opt/nodejs/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.


Then it goes through an installation and check of many things but ultimately fails with sodium still

**Comment by MBarti** [comment]
Same problem here - libsodium installation fails. Seems this plugin depends on a really old version of libsodium. I believe that probably the same issue was present with another plugin and was solved by changing the dependency. See here:
https://github.com/lprhodes/homebridge-apple-tv/issues/43#issuecomment-449105662

@edc1591, maybe this is the same problem that you can fix in a similar way?

**Comment by jblakeney82** [comment]
Do you know the Libsodium version required?

**Comment by MBarti** [comment]
Oh, it seems the guy that fixed the other plugin also forked and possibly fixed this one...
https://github.com/pponce/homebridge-theater-mode

He updated the dependency to his own fork of node-appletv, which in turn updates the libsodium dependency to version 3.0.1

**Comment by MBarti** [comment]
Ok, got it working now! Took 1h and multiple warnings for some reason, but it finally installed.
Looks like many people forked this plugin to fix the dependency, e.g. also here:
https://github.com/mitchelp/homebridge-theater-mode

Try:
npm install -g pponce/homebridge-theater-mode --unsafe-perm
or:
npm install -g mitchelp/homebridge-theater-mode --unsafe-perm

**Comment by jblakeney82** [comment]
Did you do this with the current libsodium version?

**Comment by MBarti** [comment]
I didn't do anything - just installed the fork of the homebridge-theater-mode plugin with the above command and it worked.

Unfortunately the plugin itself is very slow - sometimes 20-30 seconds for the status to update :(

**Comment by StefaanD** [comment]
Neither the fork from ponce or mitchelp worked for me, still get the same sodium error message which others have posted here.

**Comment by MBarti** [comment]
I also upgraded my node version before installation, to the latest one 11.10.1, maybe that will help you? Warning: it requires all other home bridge plugins to be rebuilt or reinstalled.
https://thisdavej.com/upgrading-to-more-recent-versions-of-node-js-on-the-raspberry-pi/

**Comment by gmum4d** [comment]
As this issue has not been resolved and the plug-in has not been updated in a year, Is it safe to assume that this plug-in is dead.

**Comment by andeoldemeu** [comment]
Good morning all !
I dig up the subject to find out if some have solved the problem with sodium?
This plugin is really useful and will be more and more! @evandcoleman , do you think you can fix the bugs?

**Comment by Jorick-tv** [comment]
Sadly still not working with sodium error
