### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by willgonz** [edc1591/homebridge-theater-mode#5]
****Update Sodium 2.0.3 crashes when installing****  
[https://github.com/paixaop/node-sodium/issues/129](https://github.com/paixaop/node-sodium/issues/129)

Scroll all the way down.

_modules\node-appletv\node_modules\sodium\build\sodium.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\willgonz\AppData\Roaming\npm\node_modules\node-appletv\node_modules\sodium
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
C:\Users\willgonz\AppData\Roaming\npm\node_modules\node-appletv\node_modules\sodium\install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: node-gyp rebuild exited with code 1
    at ChildProcess.<anonymous> (C:\Users\willgonz\AppData\Roaming\npm\node_modules\node-appletv\node_modules\sodium\install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\willgonz\AppData\Roaming\npm-cache\_logs\2018-04-28T20_36_54_683Z-debug.log

**Comment by jausto** [comment]
same

**Comment by cicloid** [comment]
Try following the instructions for `node-gyp` on Windows: https://github.com/nodejs/node-gyp#on-windows

**Comment by RienduPre** [comment]
Same kind of error on Linux (RPi)

**Comment by jblakeney82** [comment]
Hi, 

I cannot for the life of me get this to install. I have search and tried every suggestion and still fails with the lib tools and libsodium errors...

**Comment by bfulham** [comment]
I have had heaps of issues with the install and have gotten up to this point and cant get any further. I have been working on this issue for 2 days now and cant get any were. None of the fixes on any other forums helped. Can someone who know this issue please help, it would be a big relief to have this fixed.

I get this error when trying to install theater mode and node-appletv:

/usr/local/lib/node_modules/homebridge-theater-mode/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-theater-mode/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-09T00_24_41_463Z-debug.log

**Comment by Henke30** [comment]
same issue on DSM-docker :(

libtool is required, but wasn't found on this system
make: *** [Makefile:62: libsodium] Error 1
/homebridge/node_modules/homebridge-theater-mode/node_modules/sodium/install.js:293
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/homebridge/node_modules/homebridge-theater-mode/node_modules/sodium/install.js:293:19)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@3.0.2 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@3.0.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-02T14_44_20_809Z-debug.log

Command failed. Please review log for details.
