### ISSUE TITLE
Problem with Installation (Ubuntu)

### ISSUE THREAD

**Issue by sadden3194** [edc1591/homebridge-theater-mode#7]
I would like to install this plugin - but if fails:

```
Makefile:80: recipe for target 'nodesodium' failed
make: *** [nodesodium] Error 1
/usr/local/lib/node_modules/homebridge-theater-mode/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-theater-mode/node_modules/sodium/install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
/usr/local/lib
└── (empty)

npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-theater-mode"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 install script 'node install.js --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
npm ERR! code 1
```

**Comment by Aekung** [comment]
Try installing with 

`npm install -g --unsafe-perm homebridge-theater-mode`

It will take you quite some times but it should be able to install without a problem.

You should also try the same command with node-appletv.

**Comment by sadden3194** [comment]
sorry but this doesn't solve the problem :/

```
> sodium@2.0.3 preinstall /usr/local/lib/node_modules/.staging/sodium-c57913c1
> node install.js --preinstall

Static libsodium was not found at /usr/local/lib/node_modules/.staging/sodium-c57913c1/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
Makefile:61: recipe for target 'libsodium' failed
make: *** [libsodium] Error 1
/usr/local/lib/node_modules/.staging/sodium-c57913c1/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.staging/sodium-c57913c1/install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
/usr/local/lib
└── (empty)

npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-theater-mode"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script 'node install.js --preinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
npm ERR! code 1

```

**Comment by sadden3194** [comment]
no help anymore ? :(

**Comment by henry-spanka** [comment]
Use `yarn global add homebridge-theater-mode` instead

**Comment by evandcoleman** [comment]
Closing this. If you're still having issues please reopen.
