### ISSUE TITLE
"The requested accessory '" + name + "' was not registered by any plugin."

### ISSUE THREAD

**Issue by cjdrawdy** [edc1591/homebridge-theater-mode#9]
Running into this issue: Homebridge Theater Mode works when manually executing homebridge, but not when configuring for systemctl. Please advise.

Aug 26 03:23:26 raspberrypi homebridge[1465]: [2018-8-26 03:23:26] Loaded config.json with 1 accessories and 1 platforms.
Aug 26 03:23:26 raspberrypi homebridge[1465]: [2018-8-26 03:23:26] ---
Aug 26 03:23:27 raspberrypi homebridge[1465]: [2018-8-26 03:23:27] Loaded plugin: homebridge-smartthings
Aug 26 03:23:27 raspberrypi homebridge[1465]: [2018-8-26 03:23:27] Registering platform 'homebridge-smartthings.SmartThings'
Aug 26 03:23:27 raspberrypi homebridge[1465]: [2018-8-26 03:23:27] ---
Aug 26 03:23:27 raspberrypi homebridge[1465]: [2018-8-26 03:23:27] Loading 1 platforms...
Aug 26 03:23:27 raspberrypi homebridge[1465]: [2018-8-26 03:23:27] [SmartThings] Initializing homebridge-smartthings.SmartThings platform...
Aug 26 03:23:27 raspberrypi homebridge[1465]: [2018-8-26 03:23:27] [SmartThings] Fetching Smart Things devices.
Aug 26 03:23:27 raspberrypi homebridge[1465]: [2018-8-26 03:23:27] Loading 1 accessories...
Aug 26 03:23:27 raspberrypi homebridge[1465]: /usr/lib/node_modules/homebridge/lib/api.js:64
Aug 26 03:23:27 raspberrypi homebridge[1465]:       throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
Aug 26 03:23:27 raspberrypi homebridge[1465]:       ^
Aug 26 03:23:27 raspberrypi homebridge[1465]: Error: The requested accessory 'AppleTVTheaterMode' was not registered by any plugin.
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:285:42)
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at Module._compile (module.js:652:30)
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at Object.Module._extensions..js (module.js:663:10)
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at Module.load (module.js:565:32)
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at tryModuleLoad (module.js:505:12)
Aug 26 03:23:27 raspberrypi homebridge[1465]:     at Function.Module._load (module.js:497:3)
Aug 26 03:23:27 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Aug 26 03:23:27 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Aug 26 03:23:27 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Aug 26 03:23:37 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.

config.json - Credentials Redacted

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
  "accessories": [
    {
      "accessory": "AppleTVTheaterMode",
      "name": "Living Room Apple TV",
      "credentials": “XXXX”
    }
  ],
"platforms": [
   {
       "platform": "homebridge-smartthings.SmartThings",
        "name": "SmartThings",
        "app_url": “XXXX”,
        "app_id": “XXXX”,
        "access_token": “XXXX”,
        "polling_seconds": 3600,
        "update_method": "direct",
        "api_seconds": 30
    }
]
}

**Comment by evandcoleman** [comment]
What's the output of `which appletv`?
